"""Regenerate the backend test fixtures under ``tests/backend/test_data/``.

Every file this script writes is **fully synthetic** — random numbers from a fixed
seed, trivial textbook SMILES (methane, ethanol, benzene, ...), placeholder
molecule names, and stub PDB files. Nothing here is derived from any real
challenge dataset, so the fixtures are safe to publish.

The shapes are the minimum the test suite needs:

* activity ground truth / submissions: ``ACTIVITY_DATASET_SIZE`` rows (the
  submission validators check the row count against that constant).
* bootstrap-score fixtures: ``BOOTSTRAP_SAMPLES`` samples per endpoint plus a
  macro ("MA") block, built with the real ``compute_macro_bootstrap_results`` so
  ``test_compute_macro_bootstrap_results_matches_fixture`` stays exact.
* structure fixtures: a small set of stub structures (no test parses PDB
  content or checks the count against ``STRUCTURE_DATASET_SIZE``).

Run from the repo root after changing endpoint names / sizes in
``backend/config.py``::

    python tests/backend/generate_test_data.py
"""

from __future__ import annotations

import sys
import zipfile
from pathlib import Path

import numpy as np
import pandas as pd

# Allow ``python tests/backend/generate_test_data.py`` from the repo root without
# installing the package (pytest itself gets this via pytest.ini's pythonpath).
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from backend.config import (  # noqa: E402
    ACTIVITY_DATASET_SIZE,
    ACTIVITY_METRICS,
    BOOTSTRAP_SAMPLES,
    CLASSIFICATION_ENDPOINTS,
    CLASSIFICATION_METRICS,
    REGRESSION_CREDIBLE_INTERVALS_LOWER_SUFFIX,
    REGRESSION_CREDIBLE_INTERVALS_UPPER_SUFFIX,
    REGRESSION_ENDPOINTS,
)
from backend.evaluate_predictions import (  # noqa: E402
    compute_macro_bootstrap_results,
)

SEED = 20240101
DATA_DIR = Path(__file__).parent / "test_data"
N_STRUCTURES = 12

# Trivial, universally known molecules — no connection to any dataset.
SMILES_POOL = [
    "C",
    "CC",
    "CCC",
    "CCCC",
    "CCO",
    "CCN",
    "CC=O",
    "CC(=O)O",
    "CO",
    "CN",
    "CS",
    "C=C",
    "C#N",
    "c1ccccc1",
    "c1ccncc1",
    "CC(C)O",
    "CCOCC",
    "CC(=O)N",
    "C1CCCCC1",
    "OCC(O)CO",
]

PDB_STUB = """\
HEADER    SYNTHETIC TEST STRUCTURE
REMARK    Fully synthetic placeholder generated by generate_test_data.py
REMARK    Contains no real structural data.
ATOM      1  N   ALA A   1       0.000   0.000   0.000  1.00  0.00           N
ATOM      2  CA  ALA A   1       1.458   0.000   0.000  1.00  0.00           C
ATOM      3  C   ALA A   1       2.009   1.420   0.000  1.00  0.00           C
ATOM      4  O   ALA A   1       1.251   2.390   0.000  1.00  0.00           O
HETATM    5  C1  LIG B   1       5.000   5.000   5.000  1.00  0.00           C
END
"""


def _molecule_names(n: int) -> list[str]:
    return [f"MOL-{i:05d}" for i in range(1, n + 1)]


def _smiles(n: int) -> list[str]:
    return [SMILES_POOL[i % len(SMILES_POOL)] for i in range(n)]


def build_activity_ground_truth(rng: np.random.Generator) -> pd.DataFrame:
    """Ground-truth activity dataset: regression values + credible intervals,
    classification labels, and a few genuine gaps per endpoint.
    """
    n = ACTIVITY_DATASET_SIZE
    df = pd.DataFrame({"SMILES": _smiles(n), "Molecule_Name": _molecule_names(n)})

    for endpoint in REGRESSION_ENDPOINTS:
        values = rng.uniform(2.0, 9.0, size=n)
        half_width = rng.uniform(0.1, 0.6, size=n)
        df[endpoint] = values
        df[f"{endpoint}{REGRESSION_CREDIBLE_INTERVALS_LOWER_SUFFIX}"] = (
            values - half_width
        )
        df[f"{endpoint}{REGRESSION_CREDIBLE_INTERVALS_UPPER_SUFFIX}"] = (
            values + half_width
        )

    for endpoint in CLASSIFICATION_ENDPOINTS:
        df[endpoint] = rng.random(n) < 0.45

    # A handful of real gaps: regression endpoints (except the 2nd) and the first
    # classification endpoint each miss a few compounds. The suite needs at least
    # one missing classification label and tolerates missing regression labels.
    gap_endpoints = [
        e for i, e in enumerate(REGRESSION_ENDPOINTS) if i != 1
    ] + CLASSIFICATION_ENDPOINTS[:1]
    for offset, endpoint in enumerate(gap_endpoints):
        gap_rows = [5 + offset, 25 + offset, 60 + offset]
        if endpoint in CLASSIFICATION_ENDPOINTS:
            df[endpoint] = df[endpoint].astype(object)
        df.loc[gap_rows, endpoint] = np.nan
        if endpoint in REGRESSION_ENDPOINTS:
            df.loc[
                gap_rows, f"{endpoint}{REGRESSION_CREDIBLE_INTERVALS_LOWER_SUFFIX}"
            ] = np.nan
            df.loc[
                gap_rows, f"{endpoint}{REGRESSION_CREDIBLE_INTERVALS_UPPER_SUFFIX}"
            ] = np.nan

    return df


def build_activity_submission(
    ground_truth: pd.DataFrame, rng: np.random.Generator, noise: float
) -> pd.DataFrame:
    """A complete (no gaps) prediction set: ground truth + Gaussian noise for
    regression endpoints, mostly-correct labels for classification endpoints.
    """
    n = len(ground_truth)
    df = ground_truth[["SMILES", "Molecule_Name"]].copy()

    for endpoint in REGRESSION_ENDPOINTS:
        true = ground_truth[endpoint].to_numpy(dtype=float)
        filled = np.where(np.isnan(true), 5.5, true)
        df[endpoint] = filled + rng.normal(0.0, noise, size=n)

    for endpoint in CLASSIFICATION_ENDPOINTS:
        true = ground_truth[endpoint].to_numpy()
        as_bool = np.array([bool(v) if not pd.isna(v) else False for v in true])
        flip = rng.random(n) < 0.15
        df[endpoint] = np.where(flip, ~as_bool, as_bool)

    return df


def _raw_bootstrap_block(
    endpoints: list[str],
    metric_ranges: dict[str, tuple[float, float]],
    rng: np.random.Generator,
) -> pd.DataFrame:
    frames = []
    for endpoint in endpoints:
        block = {"Sample": np.arange(BOOTSTRAP_SAMPLES), "Endpoint": endpoint}
        for metric, (low, high) in metric_ranges.items():
            block[metric] = rng.uniform(low, high, size=BOOTSTRAP_SAMPLES)
        frames.append(pd.DataFrame(block))
    return pd.concat(frames, ignore_index=True)


def build_bootstrap_scores(
    endpoints: list[str],
    metrics: list[tuple[str, object]],
    metric_ranges: dict[str, tuple[float, float]],
    rng: np.random.Generator,
) -> pd.DataFrame:
    """Per-endpoint bootstrap metrics plus the macro ('MA') block, the MA rows
    built with the real pipeline function so the recompute test matches exactly.
    """
    raw = _raw_bootstrap_block(endpoints, metric_ranges, rng)
    macro = compute_macro_bootstrap_results(raw, metrics=metrics)
    ordered_cols = ["Sample", "Endpoint", *[name for name, _ in metrics]]
    return pd.concat([raw, macro], ignore_index=True)[ordered_cols]


def build_structure_fixtures() -> pd.DataFrame:
    names = [f"STRUCT-{i:04d}" for i in range(1, N_STRUCTURES + 1)]
    identifiers = pd.DataFrame(
        {
            "Molecule_Name": names,
            "phase": [1 if i % 2 else 2 for i in range(N_STRUCTURES)],
        }
    )
    zip_path = DATA_DIR / "structure-submissions" / "structures.zip"
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for name in names:
            zf.writestr(f"{name}.pdb", PDB_STUB)
    return identifiers


def main() -> None:
    rng = np.random.default_rng(SEED)
    (DATA_DIR / "activity-dataset").mkdir(parents=True, exist_ok=True)
    (DATA_DIR / "activity-submissions").mkdir(parents=True, exist_ok=True)
    (DATA_DIR / "activity-scores").mkdir(parents=True, exist_ok=True)
    (DATA_DIR / "structure-submissions").mkdir(parents=True, exist_ok=True)

    ground_truth = build_activity_ground_truth(rng)
    ground_truth.to_parquet(
        DATA_DIR / "activity-dataset" / "activity-dataset.parquet", index=False
    )

    submission_parquet = build_activity_submission(ground_truth, rng, noise=0.35)
    submission_parquet.to_parquet(
        DATA_DIR / "activity-submissions" / "example-submission.parquet", index=False
    )

    submission_csv = build_activity_submission(ground_truth, rng, noise=0.8)
    submission_csv.to_csv(
        DATA_DIR / "activity-submissions" / "example-submission.csv",
        index=False,
    )

    regression_scores = build_bootstrap_scores(
        REGRESSION_ENDPOINTS,
        ACTIVITY_METRICS,
        {
            "ST-RAE": (0.05, 0.25),
            "MAE": (0.20, 0.35),
            "R2": (0.85, 0.97),
            "Spearman_R": (0.80, 0.98),
            "Kendall_Tau": (0.65, 0.90),
        },
        rng,
    )
    regression_scores.to_parquet(
        DATA_DIR / "activity-scores" / "example-bootstrap-scores-regression.parquet",
        index=False,
    )

    classification_scores = build_bootstrap_scores(
        CLASSIFICATION_ENDPOINTS,
        CLASSIFICATION_METRICS,
        {
            "MCC": (-0.10, 0.15),
            "Accuracy": (0.43, 0.57),
            "Precision": (0.02, 0.40),
            "Recall": (0.20, 0.70),
            "F1": (0.03, 0.47),
        },
        rng,
    )
    classification_scores.to_parquet(
        DATA_DIR
        / "activity-scores"
        / "example-bootstrap-scores-classification.parquet",
        index=False,
    )

    identifiers = build_structure_fixtures()
    identifiers.to_parquet(
        DATA_DIR / "structure-submissions" / "structure-identifiers.parquet",
        index=False,
    )

    print("Wrote:")
    for path in sorted(DATA_DIR.rglob("*")):
        if path.is_file():
            print(f"  {path.relative_to(DATA_DIR)}  ({path.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
